Update autoUpdate.yml

diff --git a/.github/workflows/autoUpdate.yml b/.github/workflows/autoUpdate.yml
--- a/.github/workflows/autoUpdate.yml
+++ b/.github/workflows/autoUpdate.yml
@@ -26,8 +26,6 @@ jobs:
     - name: Update submodules to the latest commit
       run: |
         git submodule update --init --recursive --depth=1  # Initialize all submodules first
-        git submodule foreach --recursive 'git checkout $(git rev-parse --abbrev-ref HEAD) && git pull --depth=1 origin || echo 
-"Failed to update submodule"'
+        git submodule foreach --recursive 'git checkout $(git rev-parse --abbrev-ref HEAD) && git pull --depth=1 origin || echo "Failed to update submodule"'
     - name: Commit and push submodule changes
-      run: git diff --quiet && git diff --staged --quiet || (git add . && git commit -m "Updated submodules" && git push 
---force-with-lease || echo "Push failed")
+      run: git diff --quiet && git diff --staged --quiet || (git add . && git commit -m "Updated submodules" && git push --force-with-lease || echo "Push failed")
